name: Release
run-name: ${{ github.actor }} is releasing ${{ github.ref_name }}

# run on all tags starting with v
on:
  push:
    tags:
      - "v**"

jobs:
  check-branch:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'
      - name: Check branch
        run: |
          branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
          if [[ $branch == main ]]; then
            echo "This workflow is running on the main branch"
            echo "CANCEL=false" >> $GITHUB_ENV
          else 
            echo "This workflow is running on $branch and not on the main branch"
            echo "CANCEL=true" >> $GITHUB_ENV
          fi
      - name: Cancel Workflow if not on main
        uses: actions/github-script@v6
        if: ${{ env.CANCEL == 'true' }}
        with:
          script: |
            github.rest.actions.cancelWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId
            });


  build:
    runs-on: ubuntu-latest
    needs: check-branch
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: fregante/setup-git-user@v2
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.25' # The Go version to download (if necessary) and use.
      - name: Delete tag from main branch
        run: |
          git tag -d ${{ github.ref_name }}
          git push --delete origin ${{ github.ref }}
      - name: Create new branch from tag
        run: git checkout -b release/${{ github.ref_name }}
      - name: Set version in plugin.yaml
        run: |
          tag=${{ github.ref_name }}
          tag=${tag#v} yq e -i '.version = env(tag)' plugin.yaml
      - run: make
      - name: Commit plugin.yaml and binaries
        run: | 
          git add -f plugin.yaml
          git add -f bin
          git commit -m "ci: built binaries for ${{ github.ref_name }}"
      - name: Tag and push
        run: |
          git tag ${{ github.ref_name }}
          git push origin release/${{ github.ref_name }} --follow-tags --force
      - name: Create github release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${tag}" \
            --generate-notes
